application: brewdonkey
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/css/images/favicon.ico
  
- url: .*
  script: handlers.py
  
