COMMENT_TYPES = (
    (1, 'Feedback'),
    (2, 'Revision')
    )


COUNTRIES = (
('us', ('United States')),
('af', ('Afghanistan')),
('al', ('Albania')),
('dz', ('Algeria')),
('as', ('American Samoa')),
('ad', ('Andorra')),
('ao', ('Angola')),
('ai', ('Anguilla')),
('aq', ('Antarctica')),
('ag', ('Antigua And Barbuda')),
('ar', ('Argentina')),
('am', ('Armenia')),
('aw', ('Aruba')),
('au', ('Australia')),
('at', ('Austria')),
('az', ('Azerbaijan')),
('bs', ('Bahamas')),
('bh', ('Bahrain')),
('bd', ('Bangladesh')),
('bb', ('Barbados')),
('by', ('Belarus')),
('be', ('Belgium')),
('bz', ('Belize')),
('bj', ('Benin')),
('bm', ('Bermuda')),
('bt', ('Bhutan')),
('bo', ('Bolivia')),
('ba', ('Bosnia And Herzegovina')),
('bw', ('Botswana')),
('br', ('Brazil')),
('io', ('British Indian Ocean Territory')),
('bn', ('Brunei Darussalam')),
('bg', ('Bulgaria')),
('bf', ('Burkina Faso')),
('bi', ('Burundi')),
('kh', ('Cambodia')),
('cm', ('Cameroon')),
('ca', ('Canada')),
('cv', ('Cape Verde')),
('ky', ('Cayman Islands')),
('cf', ('Central African Republic')),
('td', ('Chad')),
('cl', ('Chile')),
('cn', ('China')),
('co', ('Colombia')),
('km', ('Comoros')),
('cg', ('Congo')),
('ck', ('Cook Islands')),
('cr', ('Costa Rica')),
('ci', ('Cote D')),
('hr', ('Croatia')),
('cu', ('Cuba')),
('cy', ('Cyprus')),
('cz', ('Czech Republic')),
('dk', ('Denmark')),
('dj', ('Djibouti')),
('dm', ('Dominica')),
('do', ('Dominican Republic')),
('ec', ('Ecuador')),
('eg', ('Egypt')),
('sv', ('El Salvador')),
('gq', ('Equatorial Guinea')),
('er', ('Eritrea')),
('ee', ('Estonia')),
('et', ('Ethiopia')),
('fk', ('Falkland Islands (Malvinas)')),
('fo', ('Faroe Islands')),
('fm', ('Federated States Of Micronesia')),
('fj', ('Fiji')),
('fi', ('Finland')),
('fr', ('France')),
('gf', ('French Guiana')),
('pf', ('French Polynesia')),
('ga', ('Gabon')),
('gm', ('Gambia')),
('ge', ('Georgia')),
('de', ('Germany')),
('gh', ('Ghana')),
('gi', ('Gibraltar')),
('gr', ('Greece')),
('gl', ('Greenland')),
('gd', ('Grenada')),
('gp', ('Guadeloupe')),
('gu', ('Guam')),
('gt', ('Guatemala')),
('gn', ('Guinea')),
('gw', ('Guinea-Bissau')),
('gy', ('Guyana')),
('ht', ('Haiti')),
('va', ('Holy See (Vatican City State)')),
('hn', ('Honduras')),
('hk', ('Hong Kong')),
('hu', ('Hungary')),
('is', ('Iceland')),
('in', ('India')),
('id', ('Indonesia')),
('iq', ('Iraq')),
('ie', ('Ireland')),
('ir', ('Islamic Republic Of Iran')),
('il', ('Israel')),
('it', ('Italy')),
('jm', ('Jamaica')),
('jp', ('Japan')),
('jo', ('Jordan')),
('kz', ('Kazakhstan')),
('ke', ('Kenya')),
('ki', ('Kiribati')),
('kw', ('Kuwait')),
('kg', ('Kyrgyzstan')),
('la', ("Lao People's Democratic Republic")),
('lv', ('Latvia')),
('lb', ('Lebanon')),
('ls', ('Lesotho')),
('lr', ('Liberia')),
('ly', ('Libyan Arab Jamahiriya')),
('li', ('Liechtenstein')),
('lt', ('Lithuania')),
('lu', ('Luxembourg')),
('mo', ('Macao')),
('mg', ('Madagascar')),
('mw', ('Malawi')),
('my', ('Malaysia')),
('mv', ('Maldives')),
('ml', ('Mali')),
('mt', ('Malta')),
('mq', ('Martinique')),
('mr', ('Mauritania')),
('mu', ('Mauritius')),
('yt', ('Mayotte')),
('mx', ('Mexico')),
('mc', ('Monaco')),
('mn', ('Mongolia')),
('ms', ('Montserrat')),
('ma', ('Morocco')),
('mz', ('Mozambique')),
('mm', ('Myanmar')),
('na', ('Namibia')),
('nr', ('Nauru')),
('np', ('Nepal')),
('nl', ('Netherlands')),
('an', ('Netherlands Antilles')),
('nc', ('New Caledonia')),
('nz', ('New Zealand')),
('ni', ('Nicaragua')),
('ne', ('Niger')),
('ng', ('Nigeria')),
('nu', ('Niue')),
('nf', ('Norfolk Island')),
('mp', ('Northern Mariana Islands')),
('no', ('Norway')),
('om', ('Oman')),
('pk', ('Pakistan')),
('pw', ('Palau')),
('ps', ('Palestinian Territory, Occupied')),
('pa', ('Panama')),
('pg', ('Papua New Guinea')),
('py', ('Paraguay')),
('pe', ('Peru')),
('ph', ('Philippines')),
('pl', ('Poland')),
('pt', ('Portugal')),
('pr', ('Puerto Rico')),
('qa', ('Qatar')),
('kr', ('Republic Of Korea')),
('md', ('Republic Of Moldova')),
('re', ('Reunion')),
('ro', ('Romania')),
('ru', ('Russian Federation')),
('rw', ('Rwanda')),
('kn', ('Saint Kitts And Nevis')),
('lc', ('Saint Lucia')),
('vc', ('Saint Vincent And The Grenadines')),
('ws', ('Samoa')),
('sm', ('San Marino')),
('st', ('Sao Tome And Principe')),
('sa', ('Saudi Arabia')),
('sn', ('Senegal')),
('cs', ('Serbia And Montenegro')),
('sc', ('Seychelles')),
('sl', ('Sierra Leone')),
('sg', ('Singapore')),
('sk', ('Slovakia')),
('si', ('Slovenia')),
('sb', ('Solomon Islands')),
('so', ('Somalia')),
('za', ('South Africa')),
('gs', ('South Georgia And The South Sandwich Islands')),
('es', ('Spain')),
('lk', ('Sri Lanka')),
('sd', ('Sudan')),
('sr', ('Suriname')),
('sz', ('Swaziland')),
('se', ('Sweden')),
('ch', ('Switzerland')),
('sy', ('Syrian Arab Republic')),
('tw', ('Taiwan')),
('tj', ('Tajikistan')),
('th', ('Thailand')),
('cd', ('The Democratic Republic Of The Congo')),
('mk', ('The Former Yugoslav Republic Of Macedonia')),
('tl', ('Timor-Leste')),
('tg', ('Togo')),
('tk', ('Tokelau')),
('to', ('Tonga')),
('tt', ('Trinidad And Tobago')),
('tn', ('Tunisia')),
('tr', ('Turkey')),
('tm', ('Turkmenistan')),
('tv', ('Tuvalu')),
('ug', ('Uganda')),
('ua', ('Ukraine')),
('ae', ('United Arab Emirates')),
('gb', ('United Kingdom')),
('tz', ('United Republic Of Tanzania')),
('um', ('United States Minor Outlying Islands')),
('uy', ('Uruguay')),
('uz', ('Uzbekistan')),
('vu', ('Vanuatu')),
('ve', ('Venezuela')),
('vn', ('Vietnam')),
('vg', ('Virgin Islands, British')),
('vi', ('Virgin Islands, U.S.')),
('ye', ('Yemen')),
('zm', ('Zambia')),
('zw', ('Zimbabwe'))
)

def get_country_name(code):
    for c in COUNTRIES:
        if c[0] == code:
            return c[1]

def get_gender(code):
    for g in MALE_FEMALE:
        if g[0] == code:
            return g[1]
